device_model/urls.py
from django.conf.urls import url
from . import views

app_name = 'device_model'

urlpatterns = [
    # /inventory/
    url(r'^device_type_list/$', views.DeviceTypeListView.as_view(), name='device_type_list'),
    url(r'^device_type_create/$', views.DeviceTypeCreateView.as_view(), name='device_type_create'),
    url(r'^device_type_update/(?P<pk>\d+)$', views.DeviceTypeUpdateView.as_view(), name='device_type_update'),
    url(r'^device_type_view/(?P<pk>\d+)$', views.DeviceTypeDetailView.as_view(), name='device_type_view'),
    url(r'^device_type_delete/(?P<pk>\d+)$', views.DeviceTypeDeleteView.as_view(), name='device_type_delete'),

    url(r'^serdes_type_list/$', views.SerdesTypeListView.as_view(), name='serdes_type_list'),
    url(r'^serdes_type_create/$', views.SerdesTypeCreateView.as_view(), name='serdes_type_create'),
    url(r'^serdes_type_update/(?P<pk>\d+)$', views.SerdesTypeUpdateView.as_view(), name='serdes_type_update'),
    url(r'^serdes_type_view/(?P<pk>\d+)$', views.SerdesTypeDetailView.as_view(), name='serdes_type_view'),
    url(r'^serdes_type_delete/(?P<pk>\d+)$', views.SerdesTypeDeleteView.as_view(), name='serdes_type_delete'),

    url(r'^serdes_speed_list/$', views.SerdesSpeedListView.as_view(), name='serdes_speed_list'),
    url(r'^serdes_speed_create/$', views.SerdesSpeedCreateView.as_view(), name='serdes_speed_create'),
    url(r'^serdes_speed_update/(?P<pk>\d+)$', views.SerdesSpeedUpdateView.as_view(), name='serdes_speed_update'),
    url(r'^serdes_speed_view/(?P<pk>\d+)$', views.SerdesSpeedDetailView.as_view(), name='serdes_speed_view'),
    url(r'^serdes_speed_delete/(?P<pk>\d+)$', views.SerdesSpeedDeleteView.as_view(), name='serdes_speed_delete'),

    url(r'^mac_list/$', views.MacListView.as_view(), name='mac_list'),
    url(r'^mac_create/$', views.MacCreateView.as_view(), name='mac_create'),
    url(r'^mac_update/(?P<pk>\d+)$', views.MacUpdateView.as_view(), name='mac_update'),
    url(r'^mac_view/(?P<pk>\d+)$', views.MacDetailView.as_view(), name='mac_view'),
    url(r'^mac_delete/(?P<pk>\d+)$', views.MacDeleteView.as_view(), name='mac_delete'),

    url(r'^chip_list/$', views.ChipListView.as_view(), name='chip_list'),
    url(r'^chip_create/$', views.ChipCreateView.as_view(), name='chip_create'),
    url(r'^chip_update/(?P<pk>\d+)$', views.ChipUpdateView.as_view(), name='chip_update'),
    url(r'^chip_view/(?P<pk>\d+)$', views.ChipDetailView.as_view(), name='chip_view'),
    url(r'^chip_delete/(?P<pk>\d+)$', views.ChipDeleteView.as_view(), name='chip_delete'),

    url(r'^chip_model_list/$', views.ChipModelListView.as_view(), name='chip_model_list'),
    url(r'^chip_model_create/$', views.ChipModelCreateView.as_view(), name='chip_model_create'),
    url(r'^chip_model_update/(?P<pk>\d+)$', views.ChipModelUpdateView.as_view(), name='chip_model_update'),
    url(r'^chip_model_view/(?P<pk>\d+)$', views.ChipModelDetailView.as_view(), name='chip_model_view'),
    url(r'^chip_model_delete/(?P<pk>\d+)$', views.ChipModelDeleteView.as_view(), name='chip_model_delete'),

    url(r'^serdes_list/$', views.SerdesListView.as_view(), name='serdes_list'),
    url(r'^serdes_create/$', views.SerdesCreateView.as_view(), name='serdes_create'),
    url(r'^serdes_update/(?P<pk>\d+)$', views.SerdesUpdateView.as_view(), name='serdes_update'),
    url(r'^serdes_view/(?P<pk>\d+)$', views.SerdesDetailView.as_view(), name='serdes_view'),
    url(r'^serdes_delete/(?P<pk>\d+)$', views.SerdesDeleteView.as_view(), name='serdes_delete'),

    url(r'^slot_type_list/$', views.SlotTypeListView.as_view(), name='slot_type_list'),
    url(r'^slot_type_create/$', views.SlotTypeCreateView.as_view(), name='slot_type_create'),
    url(r'^slot_type_update/(?P<pk>\d+)$', views.SlotTypeUpdateView.as_view(), name='slot_type_update'),
    url(r'^slot_type_view/(?P<pk>\d+)$', views.SlotTypeDetailView.as_view(), name='slot_type_view'),
    url(r'^slot_type_delete/(?P<pk>\d+)$', views.SlotTypeDeleteView.as_view(), name='slot_type_delete'),

    url(r'^module_type_list/$', views.ModuleTypeListView.as_view(), name='module_type_list'),
    url(r'^module_type_create/$', views.ModuleTypeCreateView.as_view(), name='module_type_create'),
    url(r'^module_type_update/(?P<pk>\d+)$', views.ModuleTypeUpdateView.as_view(), name='module_type_update'),
    url(r'^module_type_view/(?P<pk>\d+)$', views.ModuleTypeDetailView.as_view(), name='module_type_view'),
    url(r'^module_type_delete/(?P<pk>\d+)$', views.ModuleTypeDeleteView.as_view(), name='module_type_delete'),

    url(r'^chip_type_list/$', views.ChipTypeListView.as_view(), name='chip_type_list'),
    url(r'^chip_type_create/$', views.ChipTypeCreateView.as_view(), name='chip_type_create'),
    url(r'^chip_type_update/(?P<pk>\d+)$', views.ChipTypeUpdateView.as_view(), name='chip_type_update'),
    url(r'^chip_type_view/(?P<pk>\d+)$', views.ChipTypeDetailView.as_view(), name='chip_type_view'),
    url(r'^chip_type_delete/(?P<pk>\d+)$', views.ChipTypeDeleteView.as_view(), name='chip_type_delete'),

    # ---- Model Numbers
    url(r'^device_model_no_list/$', views.DeviceModelNoListView.as_view(), name='device_model_no_list'),
    url(r'^device_model_no_create/$', views.DeviceModelNoCreateView.as_view(), name='device_model_no_create'),
    url(r'^device_model_no_update/(?P<pk>\d+)$', views.DeviceModelNoUpdateView.as_view(), name='device_model_no_update'),
    url(r'^device_model_no_view/(?P<pk>\d+)$', views.DeviceModelNoDetailView.as_view(), name='device_model_no_view'),
    url(r'^device_model_no_delete/(?P<pk>\d+)$', views.DeviceModelNoDeleteView.as_view(), name='device_model_no_delete'),

    url(r'^slot_model_no_list/$', views.SlotModelNoListView.as_view(), name='slot_model_no_list'),
    url(r'^slot_model_no_create/$', views.SlotModelNoCreateView.as_view(), name='slot_model_no_create'),
    url(r'^slot_model_no_update/(?P<pk>\d+)$', views.SlotModelNoUpdateView.as_view(), name='slot_model_no_update'),
    url(r'^slot_model_no_view/(?P<pk>\d+)$', views.SlotModelNoDetailView.as_view(), name='slot_model_no_view'),
    url(r'^slot_model_no_delete/(?P<pk>\d+)$', views.SlotModelNoDeleteView.as_view(), name='slot_model_no_delete'),

    url(r'^module_build_model_no_list/$', views.ModuleBuildModelNoListView.as_view(), name='module_build_model_no_list'),
    url(r'^module_build_model_no_create/$', views.ModuleBuildModelNoCreateView.as_view(), name='module_build_model_no_create'),
    url(r'^module_build_model_no_update/(?P<pk>\d+)$', views.ModuleBuildModelNoUpdateView.as_view(), name='module_build_model_no_update'),
    url(r'^module_build_model_no_view/(?P<pk>\d+)$', views.ModuleBuildModelNoDetailView.as_view(), name='module_build_model_no_view'),
    url(r'^module_build_model_no_delete/(?P<pk>\d+)$', views.ModuleBuildModelNoDeleteView.as_view(), name='module_build_model_no_delete'),

    url(r'^chip_model_no_list/$', views.ChipModelNoListView.as_view(), name='chip_model_no_list'),
    url(r'^chip_model_no_create/$', views.ChipModelNoCreateView.as_view(), name='chip_model_no_create'),
    url(r'^chip_model_no_update/(?P<pk>\d+)$', views.ChipModelNoUpdateView.as_view(), name='chip_model_no_update'),
    url(r'^chip_model_no_view/(?P<pk>\d+)$', views.ChipModelNoDetailView.as_view(), name='chip_model_no_view'),
    url(r'^chip_model_no_delete/(?P<pk>\d+)$', views.ChipModelNoDeleteView.as_view(), name='chip_model_no_delete'),


    url(r'^module_build_list/$', views.ModuleBuildListView.as_view(), name='module_build_list'),
    url(r'^module_build_create/$', views.ModuleBuildCreateView.as_view(), name='module_build_create'),
    url(r'^module_build_update/(?P<pk>\d+)$', views.ModuleBuildUpdateView.as_view(), name='module_build_update'),
    url(r'^module_build_view/(?P<pk>\d+)$', views.ModuleBuildDetailView.as_view(), name='module_build_view'),
    url(r'^module_build_delete/(?P<pk>\d+)$', views.ModuleBuildDeleteView.as_view(), name='module_build_delete'),

]

tauto/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account.regbackend import MyRegistrationView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('account.urls')),
    url(r'^workflow/', include('workflow.urls')),
    url(r'^device_model/', include('device_model.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/login/$', auth_views.LoginView.as_view(), name='auth_login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='auth_logout'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    # /password-reset/
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        from_email='elliott.castillo@sitenaut.com',
        html_email_template_name='registration/password_reset_html_email.html',
        subject_template_name='registration/password_reset_subject.txt'
    ), name='password_reset'),

    # /password-reset/done
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),

    # /password-reset/confirm
    path('password-reset/confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

device_model/forms.py
from django import forms
from .models import DeviceType, SlotType, ModuleType, ChipType, DeviceModelNo, SlotModelNo, ModuleBuildModelNo, ChipModelNo, SerdesType, SerdesSpeed, Mac, Chip, Serdes, ModuleBuild, ChipModel


class DeviceTypeForm(forms.ModelForm):
    class Meta:
        model = DeviceType
        fields = ['name']


class SerdesTypeForm(forms.ModelForm):
    class Meta:
        model = SerdesType
        fields = ['name']


class SerdesSpeedForm(forms.ModelForm):
    class Meta:
        model = SerdesSpeed
        fields = ['speed', 'unit']


class MacForm(forms.ModelForm):
    class Meta:
        model = Mac
        fields = ['speed', 'unit']


class SerdesForm(forms.ModelForm):
    class Meta:
        model = Serdes
        fields = ['name', 'speed', 'type']


class SlotTypeForm(forms.ModelForm):
    class Meta:
        model = SlotType
        fields = ['name']


class ModuleTypeForm(forms.ModelForm):
    class Meta:
        model = ModuleType
        fields = ['name']


class ChipTypeForm(forms.ModelForm):
    class Meta:
        model = ChipType
        fields = ['name']


class DeviceModelNoForm(forms.ModelForm):
    class Meta:
        model = DeviceModelNo
        fields = ['name']


class SlotModelNoForm(forms.ModelForm):
    class Meta:
        model = SlotModelNo
        fields = ['name']


class ModuleBuildModelNoForm(forms.ModelForm):
    class Meta:
        model = ModuleBuildModelNo
        fields = ['name']


class ModuleBuildForm(forms.ModelForm):
    class Meta:
        model = ModuleBuild
        fields = ['name', 'model', 'ports']


class ChipModelNoForm(forms.ModelForm):
    class Meta:
        model = ChipModelNo
        fields = ['name', 'code_name']


class ChipForm(forms.ModelForm):
    class Meta:
        model = Chip
        fields = ['name', 'model', 'type', 'macs', 'nif_serdes_num', 'nif_serdes', 'fif_serdes_num', 'fif_serdes']


class ChipModelForm(forms.ModelForm):
    class Meta:
        model = ChipModel
        fields = ['chip', 'module_build']


class ChipModelModuleBuildForm(forms.ModelForm):
    qty = forms.IntegerField(required=True)

    class Meta:
        model = ChipModel
        fields = ['chip']

device_model/templates/device_model/chip_detail.html
{% extends 'account/base2.html' %}
{% load crispy_forms_tags %}
{% load objects %}
{% block body %}
    {% include 'account/breadcrumbs.html' %}
    <section class="section novi-background section-50">
        <div class="container">
            <h1>{{ section_title }}</h1>
            <hr class="divider bg-mantis">
            <div class="row">
                <div class="col-3">
                    <a class="btn-link" href="{% url update object.pk %}">Update</a>
                </div>
                <div class="col-3">
                    <a class="btn-link" href="{% url delete object.pk %}">Delete</a>
                </div>
                <div class="col-3">
                    <a class="btn-link" href="{% url create %}">Add New</a>
                </div>
                <div class="col-3">
                    <a class="btn-link" href="{% url cancel %}">List All</a>
                </div>
            </div>
            <div class="row">
                {% if object %}
                    {{ object.name }} {{ object.model }} {{ object.type }}
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

device_model/templates/device_model/chip_list.html
{% extends 'account/base2.html' %}
{% load crispy_forms_tags %}
{% block body %}
    {% include 'account/breadcrumbs.html' %}
    <section class="section novi-background section-66 section-sm-bottom-110">
        <div class="container">
            <h1>{{ section_title }}</h1>
            <hr class="divider bg-mantis">
        <a class="btn btn-link" href="{% url create %}"><i class="fa fa-plus ml-2"></i>Add {{ section_title }}</a>
            <div class="row offset-md-top-66">
                <div class="offset-xl-2 col-xl-8">
                    <!-- Bootstrap Table-->
                    <div class="table-responsive clearfix">
                        <table class="table table-striped">
                            <tr>
                                <th>Name</th>
                            </tr>
                            {% if object_list %}
                                {% for item in object_list %}
                                    <tr>
                                        <th>
                                            <div class="btn-group btn-group-sm">
                                                <button class="btn btn-sm btn-default dropdown-toggle" type="button"
                                                        data-toggle="dropdown" aria-haspopup="true"
                                                        aria-expanded="false">{{ item }}<span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu">
                                                    <li><a href="{{ item.get_absolute_url }}">View Details</a></li>
                                                </ul>
                                            </div>
                                        </th>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

device_model/templates/device_model/chip_model_detail.html
{% extends 'account/base2.html' %}
{% load crispy_forms_tags %}
{% load objects %}
{% block body %}
    {% include 'account/breadcrumbs.html' %}
    <section class="section novi-background section-50">
        <div class="container">
            <h1>{{ section_title }}</h1>
            <hr class="divider bg-mantis">
            <div class="row">
                <div class="col-3">
                    <a class="btn-link" href="{% url update object.pk %}">Update</a>
                </div>
                <div class="col-3">
                    <a class="btn-link" href="{% url delete object.pk %}">Delete</a>
                </div>
                <div class="col-3">
                    <a class="btn-link" href="{% url create %}">Add New</a>
                </div>
                <div class="col-3">
                    <a class="btn-link" href="{% url cancel %}">List All</a>
                </div>
            </div>
            <div class="row">
                {% if object %}
                    <table class="table table-hover">
                        <thead>
                            <th>field</th>
                            <th>value</th>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Chip</td>
                                <td>{{ object.chip.model.code_name }}</td>
                            </tr>
                            <tr>
                                <td>Module</td>
                                <td>{{ object.module_build.model.name }}</td>
                            </tr>
                            <tr>
                                <td>Other Modules</td>
                                <td>
                                    {% for mod in modules %}
                                        {{ mod }}
                                    {% endfor %}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

device_model/templates/device_model/chip_model_list.html
{% extends 'account/base2.html' %}
{% load crispy_forms_tags %}
{% block body %}
    {% include 'account/breadcrumbs.html' %}
    <section class="section novi-background section-66 section-sm-bottom-110">
        <div class="container">
            <h1>{{ section_title }}</h1>
            <hr class="divider bg-mantis">
        <a class="btn btn-link" href="{% url create %}"><i class="fa fa-plus ml-2"></i>Add {{ section_title }}</a>
            <div class="row offset-md-top-66">
                <div class="offset-xl-2 col-xl-8">
                    <!-- Bootstrap Table-->
                    <div class="table-responsive clearfix">
                        <table class="table table-striped">
                            <tr>
                                <th>Name</th>
                            </tr>
                            {% if object_list %}
                                {% for item in object_list %}
                                    <tr>
                                        <th>
                                            <div class="btn-group btn-group-sm">
                                                <button class="btn btn-sm btn-default dropdown-toggle" type="button"
                                                        data-toggle="dropdown" aria-haspopup="true"
                                                        aria-expanded="false">{{ item }}<span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu">
                                                    <li><a href="{{ item.get_absolute_url }}">View Details</a></li>
                                                </ul>
                                            </div>
                                        </th>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

device_model/templates/device_model/chip_model_no_detail.html
{% extends 'account/base2.html' %}
{% load crispy_forms_tags %}
{% load objects %}
{% block body %}
    {% include 'account/breadcrumbs.html' %}
    <section class="section novi-background section-50">
        <div class="container">
            <h1>{{ section_title }}</h1>
            <hr class="divider bg-mantis">
            <div class="row">
                <div class="col-3">
                    <a class="btn-link" href="{% url update object.pk %}">Update</a>
                </div>
                <div class="col-3">
                    <a class="btn-link" href="{% url delete object.pk %}">Delete</a>
                </div>
                <div class="col-3">
                    <a class="btn-link" href="{% url create %}">Add New</a>
                </div>
                <div class="col-3">
                    <a class="btn-link" href="{% url cancel %}">List All</a>
                </div>
            </div>
            <div class="row">
                {% if object %}
                    <table class="table table-hover">
                        <thead>
                            <th>field</th>
                            <th>value</th>
                        </thead>
                        <tbody>
                            <tr>
                                <td>name</td>
                                <td>{{ object.name }}</td>
                            </tr>
                            <tr>
                                <td>code name</td>
                                <td>{{ object.code_name }}</td>
                            </tr>
                        </tbody>
                    </table>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

device_model/templates/device_model/chip_model_no_list.html
{% extends 'account/base2.html' %}
{% load crispy_forms_tags %}
{% block body %}
    {% include 'account/breadcrumbs.html' %}
    <section class="section novi-background section-66 section-sm-bottom-110">
        <div class="container">
            <h1>{{ section_title }}</h1>
            <hr class="divider bg-mantis">
        <a class="btn btn-link" href="{% url create %}"><i class="fa fa-plus ml-2"></i>Add {{ section_title }}</a>
            <div class="row offset-md-top-66">
                <div class="offset-xl-2 col-xl-8">
                    <!-- Bootstrap Table-->
                    <div class="table-responsive clearfix">
                        <table class="table table-striped">
                            <tr>
                                <th>Name</th>
                            </tr>
                            {% if object_list %}
                                {% for item in object_list %}
                                    <tr>
                                        <th>
                                            <div class="btn-group btn-group-sm">
                                                <button class="btn btn-sm btn-default dropdown-toggle" type="button"
                                                        data-toggle="dropdown" aria-haspopup="true"
                                                        aria-expanded="false">{{ item }}<span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu">
                                                    <li><a href="{{ item.get_absolute_url }}">View Details</a></li>
                                                </ul>
                                            </div>
                                        </th>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

device_model/templates/device_model/device_model_list.html
{% extends 'account/base2.html' %}
{% load crispy_forms_tags %}
{% block body %}
    {% include 'account/breadcrumbs.html' %}
    <section class="section novi-background section-66 section-sm-bottom-110">
        <div class="container">
            <h1>{{ section_title }}</h1>
            <hr class="divider bg-mantis">
        <a class="btn btn-link" href="{% url create %}"><i class="fa fa-plus ml-2"></i>Add {{ section_title }}</a>
            <div class="row offset-md-top-66">
                <div class="offset-xl-2 col-xl-8">
                    <!-- Bootstrap Table-->
                    <div class="table-responsive clearfix">
                        <table class="table table-striped">
                            <tr>
                                <th>Name</th>
                            </tr>
                            {% if object_list %}
                                {% for item in object_list %}
                                    <tr>
                                        <th>
                                            <div class="btn-group btn-group-sm">
                                                <button class="btn btn-sm btn-default dropdown-toggle" type="button"
                                                        data-toggle="dropdown" aria-haspopup="true"
                                                        aria-expanded="false">{{ item.name }}<span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu">
                                                    <li><a href="{{ item.get_absolute_url }}">View Details</a></li>
                                                </ul>
                                            </div>
                                        </th>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

device_model/templates/device_model/mac_detail.html
{% extends 'account/base2.html' %}
{% load crispy_forms_tags %}
{% load objects %}
{% block body %}
    {% include 'account/breadcrumbs.html' %}
    <section class="section novi-background section-50">
        <div class="container">
            <h1>{{ section_title }}</h1>
            <hr class="divider bg-mantis">
            <div class="row">
                <div class="col-3">
                    <a class="btn-link" href="{% url update object.pk %}">Update</a>
                </div>
                <div class="col-3">
                    <a class="btn-link" href="{% url delete object.pk %}">Delete</a>
                </div>
                <div class="col-3">
                    <a class="btn-link" href="{% url create %}">Add New</a>
                </div>
                <div class="col-3">
                    <a class="btn-link" href="{% url cancel %}">List All</a>
                </div>
            </div>
            <div class="row">
                {% if object %}
                    {{ object }}
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

device_model/templates/device_model/mac_list.html
{% extends 'account/base2.html' %}
{% load crispy_forms_tags %}
{% block body %}
    {% include 'account/breadcrumbs.html' %}
    <section class="section novi-background section-66 section-sm-bottom-110">
        <div class="container">
            <h1>{{ section_title }}</h1>
            <hr class="divider bg-mantis">
        <a class="btn btn-link" href="{% url create %}"><i class="fa fa-plus ml-2"></i>Add {{ section_title }}</a>
            <div class="row offset-md-top-66">
                <div class="offset-xl-2 col-xl-8">
                    <!-- Bootstrap Table-->
                    <div class="table-responsive clearfix">
                        <table class="table table-striped">
                            <tr>
                                <th>Name</th>
                            </tr>

                            {% if object_list %}
                                {% for item in object_list %}
                                    <tr>
                                        <th>
                                            <div class="btn-group btn-group-sm">
                                                <button class="btn btn-sm btn-default dropdown-toggle" type="button"
                                                        data-toggle="dropdown" aria-haspopup="true"
                                                        aria-expanded="false">{{ item }}<span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu">
                                                    <li><a href="{{ item.get_absolute_url }}">View Details</a></li>
                                                </ul>
                                            </div>
                                        </th>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

device_model/templates/device_model/modulebuild_form.html
{% extends 'account/base2.html' %}
{% load crispy_forms_tags %}
{% block body %}
    {% include 'account/breadcrumbs.html' %}
    <section class="section novi-background section-66">
        <div class="container">
            <h1>{{ section_title }}</h1>
            <hr class="divider bg-mantis">
            <div class="row">
                {% if object %}
                    <table class="table table-hover">
                        <tbody>
                            <tr>
                                <td>Chips:</td>
                                <td>
                                    {% for item in chips  %}
                                        {{ item }}
                                    {% endfor %}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                {% endif %}
            </div>
            <h2>Add Chips</h2>
            <hr class="divider bg-mantis">
            <form class="form-group" method="post" action="{% url 'device_model:chip_model_create' %}">
                {% csrf_token %}
                {{ chipmodel_form|crispy }}
                <input type="text" value="{{ object.pk }}" name="chip_model" hidden>
                <a class="btn btn-outline-dark ml-3" href="{% url cancel %}">Cancel</a>
                <button class="btn btn-block" type="submit">Submit</button>
            </form>

            <h2>Base</h2>
            <hr class="divider bg-mantis">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <a class="btn btn-outline-dark ml-3" href="{% url cancel %}">Cancel</a>
                <button class="btn btn-block" type="submit">Submit</button>
            </form>
        </div>
    </section>
{% endblock %}